
variables:
  #########################################
  # BSG Variables
  #########################################
  USER_NAME: "${BSG_CI_USER_NAME}"
  USER_ID: "${BSG_CI_USER_ID}"
  GROUP_NAME: "${BSG_CI_GROUP_NAME}"
  GROUP_ID: "${BSG_CI_GROUP_ID}"
  OTHER_GROUPS: "${BSG_CI_OTHER_GROUPS}"
  CORES_PER_JOB: "${BSG_CI_CORES_PER_JOB}"
  MAX_CORES: "${BSG_CI_MAX_CORES}"
  #########################################
  # GitLab Variables
  #########################################
  # Automatic
  BUILDS: "${CI_BUILDS_DIR}"
  BRANCH: "${CI_COMMIT_REF_SLUG}"
  SHA: "${CI_COMMIT_SHA}"
  REGISTRY: "${CI_REGISTRY}"
  REGISTRY_USER: "${CI_REGISTRY_USER}"
  REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}"
  REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
  HASH: "${CI_COMMIT_SHA}"
  REPO_URL: "${CI_REPOSITORY_URL}"
  REPO_NAME: "${CI_PROJECT_NAME}"
  JOB_NAME: "${CI_JOB_NAME_SLUG}"
  CACHE_KEY: "${REPO_NAME}-${BRANCH}" # Cache per-branch
  # Clone logic
  GIT_CLONE_PATH: "${BUILDS}/${REPO_NAME}-${SHA}" # Build directory shared for a commit
  GIT_STRATEGY: "none"
  GIT_SUBMODULE_STRATEGY: "none"
  GIT_CHECKOUT: "false"
  GIT_CLEAN_FLAGS: "none"
  # workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/386967
  GIT_CONFIG_COUNT: 1
  GIT_CONFIG_KEY_0: "safe.directory"
  GIT_CONFIG_VALUE_0: "*"
  # Performance flags
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  CACHE_COMPRESSION_LEVEL: "fastest"

stages:
  - validate
  - docker
  - repo

# Check for variables to make sure this is a sane configuration
undef_job:
  stage: validate
  rules:
    - if: $USER_NAME == null
    - if: $USER_ID == null
    - if: $GROUP_NAME == null
    - if: $GROUP_ID == null
    - if: $OTHER_GROUPS == null
    - if: $CORES_PER_JOB == null
    - if: $MAX_CORES == null
    - if: $BUILDS == null
    - if: $BRANCH == null
    - if: $SHA == null
    - if: $REGISTRY == null
    - if: $REGISTRY_USER == null
    - if: $REGISTRY_IMAGE == null
    - if: $REGISTRY_PASSWORD == null
    - if: $HASH == null
    - if: $REPO_URL == null
    - if: $REPO_NAME == null
    - if: $JOB_NAME == null
    - if: $CACHE_KEY == null
  script:
      - echo "[CI] Variable is not defined"
      - exit 1

###################################################
## Base Job Template
###################################################
.job_template:
  variables:
    LOG_FILE: "${JOB_NAME}.log"
  artifacts:
    when: always
    paths:
      - "*.log"
      - "*.cmd"

###################################################
## Creating the docker images
###################################################
## https://docs.gitlab.com/ee/user/packages/container_registry/build_and_push_images.html
.image_template:
  stage: docker
  #rules:
  #  - changes:
  #    - Makefile.common
  #    - Makefile.env
  #    - mk/Makefile.docker
  #    - docker/requirements.txt
  #    - docker/Dockerfile.${DOCKER_PLATFORM}
  #    - docker/entrypoint.${DOCKER_PLATFORM}.sh
  extends: .job_template
  image:
    name: docker:24.0.5
  services:
    - docker:dind
  variables:
    # GitLab variables
    GIT_STRATEGY: "fetch"
    GIT_FETCH_EXTRA_FLAGS: "--no-tags"
    GIT_CHECKOUT: "true"
    GIT_CLEAN_FLAGS: "-ffdx"
    # Globals
    CONTAINER_BUILD_IMAGE: "${REGISTRY_IMAGE}:build-${DOCKER_PLATFORM}-${SHA}"
    CONTAINER_LATEST_IMAGE: "${REGISTRY_IMAGE}:latest"
  script:
    - echo "[CI] Checking docker version"
    - docker version
    - echo "[CI] Logging into docker registry"
    - echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u ${REGISTRY_USER} --password-stdin
    - echo "[CI] Checking for latest docker image"
    - if docker manifest inspect $REGISTRY_IMAGE:latest > /dev/null 2>&1; then
        echo "[CI] $REGISTRY_IMAGE:latest exists, pulling...";
        docker pull ${CONTAINER_LATEST_IMAGE};
      else
        echo "$REGISTRY_IMAGE:latest does not exist, starting from scratch";
      fi
    - echo "[CI] Building docker image"
    - docker build docker -f docker/Dockerfile.${DOCKER_PLATFORM}
      --build-arg USER_NAME="${USER_NAME}"
      --build-arg USER_ID="${USER_ID}"
      --build-arg GROUP_NAME="${GROUP_NAME}"
      --build-arg GROUP_ID="${GROUP_ID}"
      --build-arg OTHER_GROUPS="${OTHER_GROUPS}"
      -t ${CONTAINER_BUILD_IMAGE} > ${LOG_FILE} 2>&1;
    - docker tag ${CONTAINER_BUILD_IMAGE} ${CONTAINER_LATEST_IMAGE}
    - echo "[CI] Publishing docker images"
    - docker push ${CONTAINER_BUILD_IMAGE}
    - docker push ${CONTAINER_LATEST_IMAGE}
  tags: # Use shared gitlab runner
    - saas-linux-small-amd64

build-ubuntu-image:
  extends: .image_template
  variables:
    DOCKER_PLATFORM : "ubuntu24.04"

build-centos-image:
  extends: .image_template
  variables:
    DOCKER_PLATFORM : "centos7"

###################################################
###################################################
## Creating the ${REPO_NAME} repo
###################################################
repo:
  stage: repo
  extends: .job_template
  needs:
    - job: "build-centos-image"
      optional: true
  image:
    name: "${CONTAINER_BUILD_IMAGE}"
    #entrypoint: [""]
  variables:
    # GitLab variables
    GIT_STRATEGY: "fetch"
    GIT_FETCH_EXTRA_FLAGS: "--no-tags"
    GIT_CHECKOUT: "true"
    GIT_CLEAN_FLAGS: "-ffdx"
    LOG_FILE: "${JOB_NAME}.log"
    # Globals
    DOCKER_PLATFORM: "centos7"
    CONTAINER_BUILD_IMAGE: "${REGISTRY_IMAGE}:build-${DOCKER_PLATFORM}-${SHA}"
  script:
    - echo "[CI] Doing checkout...";
    - make -j ${MAX_CORES} checkout >> ${LOG_FILE} 2>&1;
    - echo "[CI] Applying patches...";
    - make -j ${MAX_CORES} apply_patches >> ${LOG_FILE} 2>&1;

#
#
#tools_lite: ## minimal set of simulation tools
#tools_lite: apply_patches
#    @$(MAKE) build.boost
#    @$(MAKE) build.verilator
#    @$(MAKE) build.dromajo
#
#tools: ## standard tools
#tools: tools_lite
#    @$(MAKE) build.spike
#    @$(MAKE) build.surelog
#    @$(MAKE) build.yosys
#    @$(MAKE) build.yslang
#    @$(MAKE) build.axe
#
#tools_bsg: ## Additional tools for BSG users
#tools_bsg: tools
#    # Fails on first build attempt
#    @$(MAKE) build.bsg_sv2v || $(MAKE) build.bsg_sv2v
#    @$(MAKE) build.bsg_fakeram


