
# Include common GitLab CI macros
include: '.gitlab-ci.common.yml'

###################################################
## mixins
###################################################
.bp_tools_mixin:
  variables:
    REPO_NAME: "black-parrot-tools"
    # template variables
    DOCKER_PLATFORM: "setme"
    CONTAINER_IMAGE: "${REGISTRY_IMAGE}:${DOCKER_PLATFORM}"
    # used internally
    TOOLS_PACKAGE: "tools-${DOCKER_PLATFORM}"
    TOOLS_INSTALL_TAG: "${TOOLS_PACKAGE}-install"
    TOOLS_ARTIFACT: "${TOOLS_INSTALL_TAG}-${TOOL}"
    TOOLS_WILDCARD: "${TOOLS_INSTALL_TAG}-*"
    # exported to make sure things go in the right place
    BP_WORK_DIR: "${PROJECT_DIR}/${JOB_WORK_ROOT}/bp-tools-work"
    BP_INSTALL_DIR: "${PROJECT_DIR}/${JOB_WORK_ROOT}/bp-tools-install"

###################################################
## templates
###################################################

stages:
  - image
  - build
  - publish
  - run

.image_template:
  extends: [.docker_template, .bp_tools_mixin]
  stage: image
  script:
    - echo "[CI] building image ${CONTAINER_IMAGE}" | tee -a ${JOB_LOG}
    - |
      docker build docker -f docker/Dockerfile.${DOCKER_PLATFORM} \
        --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${CONTAINER_IMAGE} \
        --build-arg USER_NAME="${USER_NAME}" \
        --build-arg USER_ID="${USER_ID}" \
        --build-arg GROUP_NAME="${GROUP_NAME}" \
        --build-arg GROUP_ID="${GROUP_ID}" \
        --build-arg OTHER_GROUPS="${OTHER_GROUPS}" \
        -t ${CONTAINER_IMAGE} >> ${JOB_LOG} 2>&1
  rules:
    - !reference [.docker_template, rules]
    - changes:
        paths:
          # variable expansion of DOCKER_PLATFORM doesn't seem to work here
          - docker/Dockerfile.*
          - docker/entrypoint.*
          - docker/requirements.txt

.tool_template:
  extends: [.repo_template, .bp_tools_mixin]
  stage: build
  variables:
    TOOL: "setme"
  script:
    - echo "[CI] doing makefile checkout" | tee -a ${JOB_LOG}
    - make -j${CORES_PER_JOB} checkout >> ${JOB_LOG} 2>&1
    - echo "[CI] repatching ${TOOL}" | tee -a ${JOB_LOG}
    - make -j${CORES_PER_JOB} repatch.${TOOL} >> ${JOB_LOG} 2>&1
    - echo "[CI] rebuilding ${TOOL}" | tee -a ${JOB_LOG}
    - make -j${CORES_PER_JOB} rebuild.${TOOL} >> ${JOB_LOG} 2>&1
    - echo "[CI] moving installation directory to build output" | tee -a ${JOB_LOG}
    - mv ${BP_INSTALL_DIR} ${JOB_SUCCESS_ROOT}/${TOOLS_ARTIFACT}
  rules: !reference [.repo_template, rules]

.publish_template:
  extends: [.upload_template, .bp_tools_mixin]
  stage: publish
  variables:
    # template variables
    API_PACKAGE_NAME: "${TOOLS_PACKAGE}"
    API_PACKAGE_VER: "${COMMIT_REF_SLUG}"
  script:
      # filtering is only necessary because we're downloading all artifacts
      #   and need to separate out the correct platform artifacts
    - cd ${JOB_DEPS_ROOT}
    - find -maxdepth 1 -type d -name "${TOOLS_WILDCARD}" -exec rsync -a {}/ ${API_PACKAGE_NAME}/ \;
  rules: !reference [.upload_template, rules]

.smoke_template:
  extends: [.download_template, .bp_tools_mixin]
  stage: run
  variables:
    TOOL: "setme"
    # template variables
    API_PACKAGE_NAME: "${TOOLS_PACKAGE}"
    API_PACKAGE_VER: "${COMMIT_REF_SLUG}"
  script:
    - ls ${JOB_DEPS_ROOT}
    - ls ${JOB_DEPS_ROOT}/${API_PACKAGE_NAME}
    - ls ${JOB_DEPS_ROOT}/${API_PACKAGE_NAME}/*
    - echo "[CI] moving download to installation directory" | tee -a ${JOB_LOG}
    - mv ${JOB_DEPS_ROOT}/${API_PACKAGE_NAME} ${BP_INSTALL_DIR} >> ${JOB_LOG} 2>&1
    - ls ${BP_INSTALL_DIR}
    - ls ${BP_INSTALL_DIR}/*
    - SMOKE_SCRIPT="./ci/smoke-${TOOL}.sh"
    - echo "[CI] running script for ${SMOKE_SCRIPT}" | tee -a ${JOB_LOG}
    - ./ci/common/run-ci.sh ${SMOKE_SCRIPT}
  rules: !reference [.download_template, rules]

###################################################
## Actual Jobs
###################################################

# We couple dependencies here while we wait for this feature
# https://gitlab.com/gitlab-org/gitlab/-/issues/423456
# needs:
#  parallel:
#    matrix:
#      - DOCKER_PLATFORM: $DOCKER_PLATFORM

build-image:
  extends: [.image_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
  rules: !reference [.image_template, rules]

build-tools:
  extends: [.tool_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["dromajo"]
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["verilator", "dromajo"]
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["spike", "surelog", "yslang", "axe"]
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["bsg_sv2v", "bsg_fakeram"]
  rules: !reference [.tool_template, rules]
  dependencies: [build-image]

publish-tools:
  extends: [.publish_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
  rules: !reference [.publish_template, rules]
  dependencies: [build-tools]

run-smoke:
  extends: [.smoke_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["verilator", "yosys"]
  rules: !reference [.smoke_template, rules]
  dependencies: [publish-tools]

