
# Include common GitLab CI macros
include: '.gitlab-ci.common.yml'

###################################################
## Mixins
###################################################
.bp_tools_mixin:
  variables:
    REPO_NAME: "black-parrot-tools"
    DOCKER_PLATFORM: "setme"
    DOCKERFILE_DIR: "docker"
    # used internally
    TOOLS_PACKAGE: "tools-${DOCKER_PLATFORM}"
    TOOLS_INSTALL_TAG: "${TOOLS_PACKAGE}-install"
    TOOLS_WILDCARD: "${JOB_DEPS_ROOT}/${TOOLS_INSTALL_TAG}-*"
    TOOLS_UPLOAD_PACKAGE: "${JOB_UPLOAD_ROOT}/${TOOLS_INSTALL_TAG}"
    TOOLS_DOWNLOAD_PACKAGE: "${JOB_DOWNLOAD_ROOT}/${TOOLS_INSTALL_TAG}"
    # exported to make sure things go in the right place
    BP_WORK_DIR: "${JOB_WORK_ROOT}/bp-tools-work"
    BP_INSTALL_DIR: "${JOB_WORK_ROOT}/bp-tools-install"

###################################################
## templates
###################################################

.image_template:
  extends: [.docker_template, .bp_tools_mixin]
  stage: image
  script:
    - |
      echo "[CI] building image ${CONTAINER_IMAGE}" | tee -a ${JOB_LOG}
      docker build docker -f ${DOCKERFILE_DIR}/Dockerfile.${DOCKER_PLATFORM} \
      --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${CONTAINER_IMAGE} \
      --build-arg USER_NAME="${USER_NAME}" \
      --build-arg USER_ID="${USER_ID}" \
      --build-arg GROUP_NAME="${GROUP_NAME}" \
      --build-arg GROUP_ID="${GROUP_ID}" \
      --build-arg OTHER_GROUPS="${OTHER_GROUPS}" \
      --build-arg WORKDIR="${WORKDIR}" \
      -t ${CONTAINER_IMAGE} >> ${JOB_LOG} 2>&1
  rules: !reference [.docker_template, rules]

.tool_template:
  extends: [.build_template, .bp_tools_mixin]
  stage: build
  variables:
    TOOL: "setme"
    # template variables
    ARTIFACT_NAME: "${TOOLS_INSTALL_TAG}-${TOOL}"
    BUILD_OUTPUT_ROOT: "${BP_INSTALL_DIR}-${TOOL}"
  script:
    - |
      echo "[CI] doing makefile checkout" | tee -a ${JOB_LOG}
      make -j${CORES_PER_JOB} checkout >> ${JOB_LOG} 2>&1
      echo "[CI] repatching ${TOOL}" | tee -a ${JOB_LOG}
      make -j${CORES_PER_JOB} repatch.${TOOL} >> ${JOB_LOG} 2>&1
      echo "[CI] rebuilding ${TOOL}" | tee -a ${JOB_LOG}
      make -j${CORES_PER_JOB} rebuild.${TOOL} >> ${JOB_LOG} 2>&1
      echo "[CI] moving output to build output" | tee -a ${JOB_LOG}
      mv ${BP_INSTALL_DIR} ${BUILD_OUTPUT_ROOT} >> ${JOB_LOG} 2>&1
  rules: !reference [.build_template, rules]

.publish_template:
  extends: [.upload_template, .bp_tools_mixin]
  stage: publish
  variables:
    # template variables
    LOCAL_PACKAGE_ROOT: "${TOOLS_UPLOAD_PACKAGE}"
    API_PACKAGE_NAME: "${TOOLS_PACKAGE}"
    API_PACKAGE_VER: "${COMMIT_REF_SLUG}"
  script:
    # this is only necessary because we're downloading all artifacts
    #   and need to separate out the correct platform artifacts
    - |
      FILTERED_TGZ=$(ls ${TOOLS_WILDCARD}) >> ${JOB_LOG} 2>&1
      echo "[CI] archives found for platform '${TOOLS_WILDCARD}': ${FILTERED_TGZ}" | tee -a ${JOB_LOG}
      for f in ${FILTERED_TGZ}; do
        tar --totals -xzf $f -C ${LOCAL_PACKAGE_ROOT} --strip-components=1 >> ${JOB_LOG} 2>&1
      done
  rules: !reference [.upload_template, rules]

.smoke_template:
  extends: [.download_template, .bp_tools_mixin]
  stage: run
  variables:
    TOOL: "setme"
    # template variables
    LOCAL_PACKAGE_ROOT: "${TOOLS_DOWNLOAD_PACKAGE}"
    API_PACKAGE_NAME: "${TOOLS_PACKAGE}"
    API_PACKAGE_VER: "${COMMIT_REF_SLUG}"
  script:
    - |
      echo "[CI] moving download to installation directory" | tee -a ${JOB_LOG}
      mv ${LOCAL_PACKAGE_ROOT} ${BP_INSTALL_DIR} >> ${JOB_LOG} 2>&1
      SMOKE_SCRIPT="./ci/smoke-${TOOL}.sh"
      echo "[CI] running script for ${SMOKE_SCRIPT}" | tee -a ${JOB_LOG}
      ./ci/common/run-ci.sh ${SMOKE_SCRIPT}
  rules: !reference [.download_template, rules]

###################################################
## Workflow
###################################################

# Currently only run on pushes, merge requests do not run separately
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ "/^ci_.*$|master/"

stages:
  - image
  - build
  - publish
  - run

###################################################
## Actual Jobs
###################################################

# We couple dependencies here while we wait for this feature
# https://gitlab.com/gitlab-org/gitlab/-/issues/423456
# needs:
#  parallel:
#    matrix:
#      - DOCKER_PLATFORM: $DOCKER_PLATFORM

build-image:
  extends: [.image_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
  rules: !reference [.image_template, rules]

build-tools:
  extends: [.tool_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["boost", "verilator", "dromajo"]
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["spike", "surelog", "yslang", "axe"]
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["bsg_sv2v", "bsg_fakeram"]
  rules: !reference [.tool_template, rules]
  dependencies: [build-image]

publish-tools:
  extends: [.publish_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
  rules: !reference [.publish_template, rules]
  dependencies: [build-tools]

run-smoke:
  extends: [.smoke_template]
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]
        TOOL: ["verilator", "yosys"]
  rules: !reference [.smoke_template, rules]
  dependencies: [publish-tools]

