
# https://docs.gitlab.com/ci/variables/predefined_variables/
variables:
  #########################################
  # Required Project Variables
  #########################################
  REPO_NAME: "setme"
  #########################################
  # Required BSG Variables
  #########################################
  USER_NAME: "${BSG_CI_USER_NAME}"
  USER_ID: "${BSG_CI_USER_ID}"
  GROUP_NAME: "${BSG_CI_GROUP_NAME}"
  GROUP_ID: "${BSG_CI_GROUP_ID}"
  OTHER_GROUPS: "${BSG_CI_OTHER_GROUPS}"
  CORES_PER_JOB: "${BSG_CI_CORES_PER_JOB}"
  JOB_LOGLEVEL: "${BSG_CI_LOG_LEVEL}"
  #########################################
  # Runner mounted locations
  #########################################
  WORKDIR: "${BSG_CI_WORKDIR}"
  CACHEDIR: "${BSG_CI_CACHEDIR}"
  BUILDDIR: "${BSG_CI_BUILDDIR}"
  COMMONDIR: "${BSG_CI_COMMONDIR}"
  CADDIR: "${BSG_CI_CADDIR}"
  #########################################
  # BSG Flags
  #########################################
  FORCE_REBUILD: "${BSG_CI_FORCE_REBUILD}"
  #########################################
  # GitLab Variables
  #########################################
  # Automatic; we save them as "documentation"
  BUILDS: "${CI_BUILDS_DIR}"
  BRANCH: "${CI_COMMIT_REF_SLUG}"
  COMMIT_REF: "${CI_COMMIT_REF_NAME}"
  REPOSITORY_URL: "${CI_REPOSITORY_URL}"
  SHA: "${CI_COMMIT_SHA}"
  JOB_NAME: "${CI_JOB_NAME_SLUG}"
  PIPELINE_ID: "${CI_PIPELINE_ID}"
  PROJECT_NAME: "${CI_PROJECT_NAME}"
  REGISTRY: "${CI_REGISTRY}"
  REGISTRY_USER: "${CI_REGISTRY_USER}"
  REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}"
  REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
  JOB_TOKEN: "${CI_JOB_TOKEN}"
  PROJECT_ID: "${CI_PROJECT_ID}"
  API_URL: "${CI_API_V4_URL}"
  PROJECT_DIR: "${CI_PROJECT_DIR}"
  CONCURRENT_ID: "${CI_CONCURRENT_PROJECT_ID}"
  # https://docs.gitlab.com/ci/runners/configure_runners/#ignore-errors-in-after_script
  AFTER_SCRIPT_IGNORE_ERRORS: false
  FF_ENABLE_BASH_EXIT_CODE_CHECK: true
  # workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/386967
  GIT_CONFIG_COUNT: 1
  GIT_CONFIG_KEY_0: "safe.directory"
  GIT_CONFIG_VALUE_0: "*"
  # Performance flags https://docs.gitlab.com/runner/configuration/feature-flags/
  FF_USE_FASTZIP: "true"
  #ARTIFACT_COMPRESSION_LEVEL: "fastest"
  #CACHE_COMPRESSION_LEVEL: "fastest"
  # Enable docker caching
  DOCKER_BUILDKIT: "1"
  DOCKER_DRIVER: "overlay2"

###################################################
## Anchors
###################################################

.git_anchors:
  variables: &git_variables
    # builtin
    GET_SOURCES_ATTEMPTS: 3
    # helper
    FETCH_BASE_FLAGS: "--jobs=${CORES_PER_JOB} --prune --no-tags"
    UPDATE_BASE_FLAGS: "--jobs=${CORES_PER_JOB} --recommend-shallow"
    REFERENCE_REPO: "${COMMONDIR}/${REPO_NAME}"
    # https://docs.gitlab.com/ci/runners/configure_runners/#handling-concurrency
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${REPO_NAME}/${CI_PIPELINE_ID}/${JOB_NAME}"
  git_prefetch: &git_prefetch_script
    - |
      echo "[CI] pre-fetching git repo from ${REFERENCE_REPO}"
      git clone --no-checkout --reference=${REFERENCE_REPO} ${REPOSITORY_URL} ${GIT_CLONE_PATH}
      echo "[CI] pre-fetching submodules from ${REFERENCE_REPO}"
      git -C ${GIT_CLONE_PATH} submodule update --init --recursive --reference=${REFERENCE_REPO}
  git_cleanup: &git_cleanup_script
    - |
      echo "[CI] cleaning up the submodules"
      git submodule deinit --force --all

###################################################
## Mixins
###################################################

.git_mixin:
  variables:
    <<: *git_variables

.bare_mixin:
  extends: [.git_mixin]
  variables:
    # Built-in
    GIT_STRATEGY: "none"
    GIT_DEPTH: ""
    GIT_FETCH_EXTRA_FLAGS: "none"
    GIT_CHECKOUT: "none"
    GIT_CLEAN_FLAGS: "none"
    GIT_SUBMODULE_STRATEGY: "none"
    GIT_SUBMODULE_UPDATE_FLAGS: "none"
    GIT_SUBMODULE_DEPTH: ""

.clone_mixin:
  extends: [.git_mixin]
  variables:
    # Built-in
    GIT_STRATEGY: "clone"
    GIT_DEPTH: "5"
    GIT_FETCH_EXTRA_FLAGS: "${FETCH_BASE_FLAGS}"
    GIT_CHECKOUT: "true"
    GIT_CLEAN_FLAGS: "none"
    GIT_SUBMODULE_STRATEGY: "none"
    GIT_SUBMODULE_UPDATE_FLAGS: "none"
    GIT_SUBMODULE_DEPTH: ""

.fetch_mixin:
  extends: [.git_mixin]
  variables:
    # Built-in
    GIT_STRATEGY: "fetch"
    GIT_DEPTH: "5"
    GIT_FETCH_EXTRA_FLAGS: "${FETCH_BASE_FLAGS}"
    GIT_CHECKOUT: "true"
    GIT_CLEAN_FLAGS: "none"
    GIT_SUBMODULE_STRATEGY: "recursive"
    GIT_SUBMODULE_UPDATE_FLAGS: "${UPDATE_BASE_FLAGS}"
    GIT_SUBMODULE_DEPTH: "3"

.api_mixin:
  variables:
    # template variables
    PACKAGE_NAME: "setme"
    PUBLISH_NAME: "setme"
    PUBLISH_VER: "${BRANCH}"
    # generated variables
    PACKAGE_DIR: "${PROJECT_DIR}/${PACKAGE_NAME}"
    PACKAGE_TGZ: "${PACKAGE_DIR}.tar.gz"
    PUBLISH_TGZ: "${PACKAGE_NAME}.tar.gz"
    # builtin variables
    PROJECT_URL: "${API_URL}/projects/${PROJECT_ID}"
    PACKAGE_URL: "${PROJECT_URL}/packages/generic/${PACKAGE_NAME}"
    PUBLISH_URL: "${PACKAGE_URL}/${PUBLISH_VER}/${PUBLISH_TGZ}"

###################################################
## Job Templates
###################################################
.job_template:
  variables:
    # default variables
    JOB_LOG: "${PROJECT_DIR}/logs/${JOB_NAME}.log"
    JOB_RPT: "${PROJECT_DIR}/reports/${JOB_NAME}.rpt"
    DOTENV: "${PROJECT_DIR}/build.env"
    # used in all jobs
    DOCKER_PLATFORM: "setme"
    CONTAINER_IMAGE: "setme"
  tags: [bsg] # use bsg machines by default
  before_script:
    - |
      echo "[CI] job running from ${CI_PROJECT_DIR}"
      echo "[CI] repo cloning to ${GIT_CLONE_PATH}"
      echo "[CI] Creating log directory"
      mkdir -p $(dirname ${JOB_LOG}) $(dirname ${JOB_RPT})
      echo "[CI] Update DOTENV"
      echo "DOTENV_TESTVAR=dotenv_testvar" | tee -a ${GITLAB_ENV} >> ${DOTENV}
      echo "[CI] Starting job ${JOB_GROUP_NAME}" | tee -a ${JOB_LOG}
  after_script:
    - |
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo "[CI] job passed with status $CI_JOB_STATUS" | tee -a ${JOB_RPT}
      else
        echo "[CI] job failed with status $CI_JOB_STATUS" | tee -a ${JOB_RPT}
      fi
      echo "Unset variables:" >> ${JOB_RPT}
      export | grep -s "setme" || true >> ${JOB_RPT}
      echo "[CI] Finishing job ${JOB_GROUP_NAME}" | tee -a ${JOB_LOG}
  artifacts:
    when: always
    paths:
      - ${JOB_LOG}
      - ${JOB_RPT}
    reports:
      dotenv: ${DOTENV}
  # Default rules
  rules: [when: on_success]
  # Default dependencies
  dependencies: []

## https://docs.gitlab.com/ee/user/packages/container_registry/build_and_push_images.html
.docker_template:
  extends: [.job_template, .clone_mixin]
  tags: [saas-linux-small-amd64] # use shared gitlab runner for dind
  image: {name: docker:24.0.5}
  services: [docker:24.0.5-dind]
  before_script:
    - !reference [.job_template, before_script]
    - |
      echo "[CI] Logging into docker registry" | tee -a ${JOB_LOG}
      echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u ${REGISTRY_USER} --password-stdin
      echo "[CI] Checking for previous docker image ${CONTAINER_IMAGE}" | tee -a ${JOB_LOG}
      if docker manifest inspect ${CONTAINER_IMAGE} > /dev/null 2>&1; then
        echo "[CI] ${CONTAINER_IMAGE} exists, pulling..." | tee -a ${JOB_LOG}
        docker pull ${CONTAINER_IMAGE}
      else
        echo "[CI] ${CONTAINER_IMAGE} does not exist, starting from scratch"  | tee -a ${JOB_LOG}
      fi
  after_script:
    - |
      echo "[CI] Logging into docker registry"  | tee -a ${JOB_LOG}
      echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u ${REGISTRY_USER} --password-stdin
      echo "[CI] Publishing docker images"  | tee -a ${JOB_LOG}
      docker push ${CONTAINER_IMAGE}
    - !reference [.job_template, after_script]
  rules:
    - if: $BSG_CI_FORCE_REBUILD == "1"
      when: always
    - changes:
        paths:
          - docker/*

# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1736#note_107983504
.repo_template:
  extends: [.job_template, .fetch_mixin]
  image: {name: "${CONTAINER_IMAGE}"}
  variables: {FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"}
  hooks: {pre_get_sources_script: !reference [.git_anchors, git_prefetch]}
  rules: !reference [.job_template, rules]

# https://docs.gitlab.com/user/packages/package_registry/
.upload_template:
  extends: [.repo_template, .api_mixin]
  after_script:
    - |
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo "[CI] Zipping installation ${PACKAGE_TGZ}" | tee -a ${JOB_LOG}
        tar --warning=no-file-changed -czvf ${PACKAGE_TGZ} -C $(dirname ${PACKAGE_DIR}) $(basename ${PACKAGE_DIR}) >> ${JOB_LOG} 2>&1
        echo "[CI] Publishing to ${PACKAGE_URL} with curl API"
        curl --location --header "JOB-TOKEN: ${JOB_TOKEN}" \
             --upload-file ${PACKAGE_TGZ} \
             ${PUBLISH_URL}
      fi
    - !reference [.repo_template, after_script]
  rules: !reference [.repo_template, rules]

# https://docs.gitlab.com/user/packages/package_registry/
.download_template:
  extends: [.repo_template, .api_mixin]
  before_script:
    - !reference [.repo_template, before_script]
    - |
      echo "[CI] Creating PACKAGE_DIR=${PACKAGE_DIR}" | tee -a ${JOB_LOG}
      mkdir -p ${PACKAGE_DIR}
      curl --location --header "JOB-TOKEN: ${JOB_TOKEN}" \
           --output ${PACKAGE_TGZ} \
           ${PUBLISH_URL}
      echo "[CI] Unzipping installation ${PACKAGE_TGZ}" | tee -a ${JOB_LOG}
      tar -xzvf ${PACKAGE_TGZ} -C ${PACKAGE_DIR} --strip-components=1 >> ${JOB_LOG} 2>&1
  rules: !reference [.repo_template, rules]

