
variables:
  # GitLab variables
  GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${CI_PROJECT_NAME}-${CI_COMMIT_SHA}" # Build directory shared for a commit
  GIT_STRATEGY: "none"
  GIT_SUBMODULE_STRATEGY: "none"
  GIT_CHECKOUT: "false"
  GIT_CLEAN_FLAGS: "none"
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  CACHE_COMPRESSION_LEVEL: "fastest"
  # Other varibles
  BSG_CADENV_DIR: "${CI_BSG_CADENV_DIR}"
  CORES_PER_JOB: "${CI_CORES_PER_JOB}"
  MISC_DIR: "${CI_MISC_DIR}"
  MAX_CORES: "${CI_MAX_CORES}"
  BRANCH: "${CI_COMMIT_REF_SLUG}"
  HASH: "${CI_COMMIT_SHA}"
  REPO_URL: "${CI_REPOSITORY_URL}"
  REPO_NAME: "${CI_PROJECT_NAME}"
  JOB_NAME: "${CI_JOB_NAME_SLUG}"
  CACHE_KEY: "${REPO_NAME}-${BRANCH}" # Cache per-branch

stages:
  - repo

###################################################
## Base Job Template
###################################################
.job_template:
  dependencies: []
  needs: []
  artifacts:
    when: always
    paths:
      - ${LOG_FILE}

###################################################
## Creating the ${REPO_NAME} repo
###################################################
repo:
  stage: repo
  extends: .job_template
  variables:
    # GitLab variables
    GIT_STRATEGY: "fetch"
    GIT_FETCH_EXTRA_FLAGS: "--no-tags"
    GIT_CHECKOUT: "true"
    GIT_CLEAN_FLAGS: "-ffdx"
    LOG_FILE: "${JOB_NAME}.log"
  script:
    - echo "[CI] Doing checkout...";
    - make -j ${MAX_CORES} checkout >> ${LOG_FILE} 2>&1;
    - echo "[CI] Applying patches...";
    - make -j ${MAX_CORES} apply_patches >> ${LOG_FILE} 2>&1;

