
trigger_job:
  variables:
    DOCKER_PLATFORM: "setme"
    CONTAINER_IMAGE: "$CI_REGISTRY_IMAGE:$DOCKER_PLATFORM"
  interruptible: true
  trigger:
    strategy: depend
    include: .gitlab-ci.local.yml
  parallel:
    matrix:
      - DOCKER_PLATFORM: ["centos7", "ubuntu24.04"]

###################################################
## workflow
###################################################
workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all
  rules:
    - if: $CI_COMMIT_BRANCH =~ "/^ci_.*$|master|main/"

