
variables:
  #########################################
  # Required BSG Variables
  #########################################
  USER_NAME: "${BSG_CI_USER_NAME}"
  USER_ID: "${BSG_CI_USER_ID}"
  GROUP_NAME: "${BSG_CI_GROUP_NAME}"
  GROUP_ID: "${BSG_CI_GROUP_ID}"
  OTHER_GROUPS: "${BSG_CI_OTHER_GROUPS}"
  CORES_PER_JOB: "${BSG_CI_CORES_PER_JOB}"
  MAX_CORES: "${BSG_CI_MAX_CORES}"
  #########################################
  # Optional BSG Variables
  #########################################
  FORCE_REBUILD: "${BSG_CI_FORCE_REBUILD}"
  #########################################
  # GitLab Variables
  #########################################
  # Automatic
  BUILDS: "${CI_BUILDS_DIR}"
  BRANCH: "${CI_COMMIT_REF_SLUG}"
  SHA: "${CI_COMMIT_SHA}"
  REGISTRY: "${CI_REGISTRY}"
  REGISTRY_USER: "${CI_REGISTRY_USER}"
  REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}"
  REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
  HASH: "${CI_COMMIT_SHA}"
  REPO_URL: "${CI_REPOSITORY_URL}"
  REPO_NAME: "${CI_PROJECT_NAME}"
  JOB_NAME: "${CI_JOB_NAME_SLUG}"
  # workaround for https://gitlab.com/gitlab-org/gitlab/-/issues/386967
  GIT_CONFIG_COUNT: 1
  GIT_CONFIG_KEY_0: "safe.directory"
  GIT_CONFIG_VALUE_0: "*"
  # Performance flags https://docs.gitlab.com/runner/configuration/feature-flags/
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  CACHE_COMPRESSION_LEVEL: "fastest"
  #########################################
  # Generated Global Variables
  #########################################
  CACHE_KEY: "${REPO_NAME}-${BRANCH}" # Cache per-branch
  CLONE_PATH: "${BUILDS}/${REPO_NAME}-${SHA}" # Clone per-commit

stages:
  - validate
  - docker
  - repo

# Check for variables to make sure this is a sane configuration
undef_job:
  stage: validate
  rules:
    - if: $USER_NAME == null
    - if: $USER_ID == null
    - if: $GROUP_NAME == null
    - if: $GROUP_ID == null
    - if: $OTHER_GROUPS == null
    - if: $CORES_PER_JOB == null
    - if: $MAX_CORES == null
    - if: $BUILDS == null
    - if: $BRANCH == null
    - if: $SHA == null
    - if: $REGISTRY == null
    - if: $REGISTRY_USER == null
    - if: $REGISTRY_IMAGE == null
    - if: $REGISTRY_PASSWORD == null
    - if: $HASH == null
    - if: $REPO_URL == null
    - if: $REPO_NAME == null
    - if: $JOB_NAME == null
  script:
      - echo "[CI] Variable is not defined"
      - exit 1

###################################################
## Job Templates
###################################################
.centos7_template:
  variables: { DOCKER_PLATFORM : "centos7" }

.ubuntu2404_template:
  variables: { DOCKER_PLATFORM: "ubuntu24.04" }

.no_clone_template:
  variables:
    # Don't fetch anything
    GIT_STRATEGY: "none"
    GIT_SUBMODULE_STRATEGY: "none"

.fetch_template:
  variables:
    # Fetch just the docker file
    GIT_STRATEGY: "fetch"
    GIT_FETCH_EXTRA_FLAGS: "--prune --progress --no-tags"
    GIT_SUBMODULE_STRATEGY: "none"

.full_clone_template:
  variables:
    # Do a full clone
    GIT_STRATEGY: "clone"
    GIT_FETCH_EXTRA_FLAGS: "--prune --progress --no-tags"
    GIT_SUBMODULE_STRATEGY: "recursive"
    GIT_SUBMODULE_UPDATE_FLAGS: "--jobs ${BSG_CI_MAX_CORES} --recommend-shallow"

.job_template:
  extends: .no_clone_template
  variables:
    LOG_FILE: "${JOB_NAME}.log"
    CONTAINER_BASE_TYPE: "setme"
    CONTAINER_BUILD_TYPE: "setme"
    CONTAINER_IMAGE: "${REGISTRY_IMAGE}:${DOCKER_PLATFORM}"
    CONTAINER_IMAGE_BASE  : "${CONTAINER_IMAGE}-${CONTAINER_BASE_TYPE}-latest"
    CONTAINER_IMAGE_SHA: "${CONTAINER_IMAGE}-${CONTAINER_BUILD_TYPE}-${SHA}"
    CONTAINER_IMAGE_LATEST: "${CONTAINER_IMAGE}-${CONTAINER_BUILD_TYPE}-latest"
    CONTAINER_EXEC: "run-${CONTAINER_BUILD_TYPE}"
  artifacts:
    when: always
    paths:
      - "*.log"

## https://docs.gitlab.com/ee/user/packages/container_registry/build_and_push_images.html
.image_template:
  stage: docker
  extends: [ .job_template, .fetch_template ]
  image: { name: docker:24.0.5 }
  services: [ docker:dind ]
  before_script:
    - echo "[CI] Checking docker version"
    - docker version
    - echo "[CI] Logging into docker registry"
    - echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u ${REGISTRY_USER} --password-stdin
    - echo "[CI] Checking for latest docker image"
    - if docker manifest inspect ${CONTAINER_IMAGE_BASE} > /dev/null 2>&1; then
        echo "[CI] ${CONTAINER_IMAGE_BASE} exists, pulling...";
        docker pull ${CONTAINER_IMAGE_BASE};
      else
        echo "[CI] ${CONTAINER_IMAGE_BASE} does not exist, starting from scratch";
      fi
  after_script:
    - echo "[CI] Updating latest docker tag"
    - docker tag ${CONTAINER_IMAGE_SHA} ${CONTAINER_IMAGE_LATEST}
    - echo "[CI] Publishing docker images"
    - docker push ${CONTAINER_IMAGE_SHA}
    - docker push ${CONTAINER_IMAGE_LATEST}
  tags: [ saas-linux-small-amd64 ] # Use shared gitlab runner
  rules:
    - if: $FORCE_REBUILD == null
      changes:
        - "docker/requirements.txt"
        - "docker/Dockerfile.${DOCKER_PLATFORM}"
        - "docker/entrypoint.${DOCKER_PLATFORM}.sh"

.build_image_template:
  extends: .image_template
  variables: { CONTAINER_BASE_TYPE: "build", CONTAINER_BUILD_TYPE: "build" }
  script:
    - echo "[CI] Building base docker image (with prereqs)"
    - docker build docker -f docker/Dockerfile.${DOCKER_PLATFORM}
      --build-arg USER_NAME="${USER_NAME}"
      --build-arg USER_ID="${USER_ID}"
      --build-arg GROUP_NAME="${GROUP_NAME}"
      --build-arg GROUP_ID="${GROUP_ID}"
      --build-arg OTHER_GROUPS="${OTHER_GROUPS}"
      -t ${CONTAINER_IMAGE_SHA} > ${LOG_FILE} 2>&1

.repo_image_template:
  extends: [ .image_template, .no_clone_template ]
  variables: { CONTAINER_BASE_TYPE: "build", CONTAINER_BUILD_TYPE: "repo" }
  script:
    - echo "[CI] Pulling base image"
    - docker pull ${CONTAINER_IMAGE_BASE}
    - echo "[CI] Starting background container"
    - docker run -d --name ${CONTAINER_EXEC} ${CONTAINER_IMAGE_BASE} tail -f /dev/null
    - echo "[CI] Cloning repo"
    - docker exec ${CONTAINER_EXEC} git clone ${REPO_URL} ${CLONE_PATH}
    - docker exec ${CONTAINER_EXEC} cd ${CLONE_PATH}
    - docker exec ${CONTAINER_EXEC} git checkout ${SHA}
    - echo "[CI] Sanity check"
    - docker exec ${CONTAINER_EXEC} pwd
    - docker exec ${CONTAINER_EXEC} ls
    - echo "[CI] Committing changes to container"
    - docker commit ${CONTAINER_EXEC} ${CONTAINER_IMAGE_SHA}
    - echo "[CI] Shutting down container"
    - docker rm ${CONTAINER_EXEC}

###################################################
## Creating and populating the docker images
###################################################
build-image-ubuntu2404:
  extends: [.build_image_template, .ubuntu2404_template]

build-image-centos7:
  extends: [.build_image_template, .centos7_template]

repo-image-ubuntu2404:
  extends: [.repo_image_template, .ubuntu2404_template]
  needs: [ {job: "build-image-ubuntu2404", optional: true} ]

repo-image-centos7:
  extends: [.repo_image_template, .centos7_template]
  needs: [ {job: "build-image-centos7", optional: true} ]

