# Based on Ubuntu
FROM ubuntu:24.04

# Info about the image
LABEL maintainer="Dan Petrisko <petrisko@cs.washington.edu>"

# Ubuntu tools
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
        apt-utils software-properties-common lsb-release tzdata uuid-dev default-jre \
        build-essential bash autoconf automake autotools-dev curl gawk wget \
        git vim bash-completion \
        python3 python3-dev python3-pip python3-venv python3-setuptools-whl \
        && apt-get clean
# Verilator
RUN apt-get update && apt-get install -y \
        git help2man perl python3 make libfl2 libfl-dev zlib1g flex bison \
        ccache mold libgoogle-perftools-dev numactl perl-doc \
        && apt-get clean
# Dromajo
RUN apt-get update && apt-get install -y \
        cmake python-is-python3 python-dev-is-python3 \
        && apt-get clean
# Spike
RUN apt-get update && apt-get install -y \
        device-tree-compiler \
        && apt-get clean
# Surelog
# Yosys
RUN apt-get update && apt-get install -y \
        pkg-config tcl tcl-dev libreadline-dev libffi-dev \
        && apt-get clean
# bsg_sv2v
RUN apt-get update && apt-get install -y \
        gperf virtualenv \
        && apt-get clean
#RUN apt-get update && apt-get install -y \
#        && apt-get clean

# Accept arguments for user and group
ARG USER_NAME
ARG USER_ID
ARG GROUP_NAME
ARG GROUP_ID

# Only create the group if it doesn't exist
RUN getent group $GROUP_ID || groupadd --gid $GROUP_ID $GROUP_NAME

# Use --no-log-init to deal with large userids creating giant log files
RUN useradd --no-log-init --uid $USER_ID --gid $GROUP_ID --shell /bin/bash --create-home $USER_NAME

# Sets working directory
WORKDIR /$USER_NAME

# Create directory for extra installation
RUN mkdir -p /opt && chgrp $GROUP_NAME /opt && chmod 775 /opt

# Sets the current user
USER $USER_NAME

# Create a python virtualenv
# This is in place of sourcing the environment
#   (https://pythonspeed.com/articles/activate-virtualenv-dockerfile/)
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY requirements.txt /opt/venv/
RUN pip install -r /opt/venv/requirements.txt

